version: "3"

volumes:
  pgdata:

services:
  # pgsql:
  #   image: postgres:14.2
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=secret
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  flashcards:
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile.prod
    environment:
      - PORT=8080
    ports: ["8080:8080"]
    # depends_on:
    #   - pgsql
    tty: true