"""Init.

Revision ID: 70440215445c
Revises: 
Create Date: 2022-04-05 18:26:23.812175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70440215445c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('definition', sa.String(length=450), nullable=False),
    sa.Column('bin', sa.Integer(), nullable=False),
    sa.Column('num_times_incorrect', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('last_read_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battles')
    # ### end Alembic commands ###
